### ISSUE TITLE
Null Pointer in DefaultAMIDictionary.getMaximumTermSize

### ISSUE THREAD

**Issue by petermr** [petermr/ami3#68]
```
@Peter Murray-Rust I was trying to create a sample dictionary (terms 10) using the syntax amidict -vv --dictionary disease --directory dictionary --input sparql_dis10 create --informat wikisparqlxml --sparqlmap name=wikidataLabel,term=wikidataLabel,wikipediaPage=wikipedia,wikidataURL=wikidata,description=wikidataDescription,wikidataAltLabel=wikidataAltLabel,_p494_icd10code=ICD_10,Hindi=hindiLabel,Hindi_AltLabel=hindialtlabel,Hindi_description=hindi,Hindi_wikipediaPage=hindiwikipedia,Tamil=tamilLabel,Tamil_AltLabel=tamilaltlabel,Tamil_description=tamil,Tamil_wikipediaPage=tamilwikipedia,Spanish=spanishLabel,Spanish_AltLabel=spanishaltlabel,Spanish_description=spanish,Urdu=urduLabel,Urdu_AltLabel=urdualtlabel,Urdu_description=urdu,Portuguese=ptLabel,Portuguese_AltLabel=ptaltlabel,Portuguese_desription=pt --transformName wikidataID=EXTRACT(wikidataURL,.*/(.*)) --synonyms=wikidataAltLabel for this SPARQL file but got the output as
.
.
java.lang.NullPointerException
        at org.contentmine.ami.dictionary.DefaultAMIDictionary.getMaximumTermSize(DefaultAMIDictionary.java:346)
        at org.contentmine.ami.dictionary.DefaultAMIDictionary.getTermsSortedBySize(DefaultAMIDictionary.java:324)
        at org.contentmine.ami.dictionary.DefaultAMIDictionary.toString(DefaultAMIDictionary.java:387)
        at java.lang.String.valueOf(Unknown Source)
.
```

**Comment by petermr** [comment]
I think this bug has been fixed in the latest commit.
